apiVersion: apps/v1
kind: Deployment
metadata:
  name: frps
  labels:
    app: frps
spec:
  selector:
    matchLabels:
      app: frps
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frps
    spec:
      containers:
      - name: frps
        image: snowdreamtech/frps:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  7000
          protocol: TCP
          name: frps
        - containerPort: 8080
          protocol: TCP
          name: http-proxy
        volumeMounts:
        - name: config
          mountPath: /etc/frp
      volumes:
        - name: config
          configMap:
            name: frps-config
      restartPolicy: Always
